### ISSUE TITLE
Navbar has Home selected on every page

### ISSUE THREAD

**Issue by sedivyj** [sedivyj/WebArcade#6]
![image](https://user-images.githubusercontent.com/41033622/107548792-b28f4e00-6b94-11eb-8fb0-5878a968f8f4.png)
![image](https://user-images.githubusercontent.com/41033622/107548837-bde27980-6b94-11eb-8e9e-4f555b8752fb.png)
![image](https://user-images.githubusercontent.com/41033622/107548887-c9ce3b80-6b94-11eb-824d-8b1e25f5c6a5.png)

**Comment by vailtra** [comment]
I will take the home link off of the index.html page

**Comment by spb1234** [comment]
FIXED
